# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquid', '0002_auto_20160920_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projekt',
            old_name='Ende',
            new_name='Enddatum',
        ),
        migrations.RenameField(
            model_name='projekt',
            old_name='Start',
            new_name='Startdatum',
        ),
    ]
