# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liquid', '0003_auto_20160920_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='angestellter',
            name='Einstellungsdatum',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='angestellter',
            name='Entlassungsdatum',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='angestellter',
            name='Name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='Titel',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
